name: Deploy Carbonor to CPanel via FTP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Create .htaccess file
      run: |
        if [ ! -f .htaccess ]; then
          echo "Options -Indexes" > .htaccess
          echo "DirectoryIndex index.php index.html" >> .htaccess
          echo "RewriteEngine On" >> .htaccess
          echo "RewriteCond %{HTTPS} off" >> .htaccess
          echo "RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]" >> .htaccess
        fi
        
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/*.md
          **/*.log
          **/.env*
          **/*.zip
          **/*.DS_Store
          **/Thumbs.db
          **/.vscode/**
          **/.idea/**
          **/*.swp
          **/*.swo
          **/*.bak
          **/*.backup